### ISSUE TITLE
Incorrect sign text in Chunk data

### ISSUE THREAD

**Issue by aremath** [Amulet-Team/Amulet-Core#120]
**Describe the bug**

When reading a world file using `load_level` and the calling `.get_chunk(x,y)`, the returned Chunk object stores the signs that are in that chunk in the entity. The signs stored in block_entities do not have text, despite the in-game signs having text.

**To Reproduce**

```
from amulet import load_level
# A world with a sign
level = load_level("worlds/test")
# A chunk in the world with a sign
chunk = level.get_chunk(5,6)
for e in c.block_entities:
    print(e.nbt)
```

And output

```
NBTFile("":{utags: {Text4: "{\"text\":\"\"}", Text3: "{\"text\":\"\"}", Text2: "{\"text\":\"\"}", Text1: "{\"text\":\"\"}"}})
NBTFile("":{utags: {Text4: "{\"text\":\"\"}", Text3: "{\"text\":\"\"}", Text2: "{\"text\":\"\"}", Text1: "{\"text\":\"\"}"}})
NBTFile("":{utags: {Text4: "{\"text\":\"\"}", Text3: "{\"text\":\"\"}", Text2: "{\"text\":\"\"}", Text1: "{\"text\":\"\"}"}})
```

**Expected behavior**
```
NBTFile("":{utags: {Text4: "{\"text\":\"\"}", Text3: "{\"text\":\"THIS SIGN\"}", Text2: "{\"text\":\"TEXT ON\"}", Text1: "{\"text\":\"THERE IS\"}"}})
NBTFile("":{utags: {Text4: "{\"text\":\"\"}", Text3: "{\"text\":\"\"}", Text2: "{\"text\":\"\"}", Text1: "{\"text\":\"THIS ONE TOO\"}"}})
NBTFile("":{utags: {Text4: "{\"text\":\"\"}", Text3: "{\"text\":\"\"}", Text2: "{\"text\":\"\"}", Text1: "{\"text\":\"WHEEE\"}"}})
```

**Screenshots**
![2021-03-08 10_06_16-saves](https://user-images.githubusercontent.com/14264747/111200899-74b08b80-857f-11eb-8ac8-046ae4e8eded.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.3 (Using Windows Subsystem for Linux)
 - Program Version:
    - amulet-core: 1.2.0b6
    - amulet-nbt: 1.0.3.7
- Python Version: 3.9.2

**Comment by gentlegiantJGC** [comment]
Java/Bedrock? game version?

**Comment by gentlegiantJGC** [comment]
After a bit of testing I have reproduced the issue in Java 1.16.
It was caused by an issue in our NBT library. I don't know how it was not spotted sooner.

**Comment by gentlegiantJGC** [comment]
Amulet-Team/Amulet-NBT/pull/12 should fix this
