### ISSUE TITLE
Open world as readonly

### ISSUE THREAD

**Issue by lizelive** [Amulet-Team/Amulet-Core#153]
**Is your feature request related to a problem? Please describe.**
Will allow for multi process code.

**Describe the solution you'd like**
Add flag to dissable checking the lock file

**Describe alternatives you've considered**
Complex fs shininigans, forked version of libary

**Additional context**

**Comment by gentlegiantJGC** [comment]
I don't think this is going to be possible.
It might theoretically be possible for Java but there would be issues if another process had the world open in edit mode.
For bedrock this wouldn't work because the leveldb can only be accessed from one thread

**Comment by gentlegiantJGC** [comment]
I am going to close this as won't fix because of what I said above.
