### ISSUE TITLE
Stop using global cache directory

### ISSUE THREAD

**Issue by lizelive** [Amulet-Team/Amulet-Core#154]
Using a single cache makes it very hard to use multi process or multi threaded code

https://github.com/Amulet-Team/Amulet-Core/blob/29ba12c0b77eb805d3585e3714bae3a1e61adafc/amulet/api/cache.py#L24

Proposal to fix is change this to return a new one every time and have caller deal with life cycle.

**Comment by gentlegiantJGC** [comment]
I am going to move this bug to our main bug tracker
