### ISSUE TITLE
Sign text not getting set

### ISSUE THREAD

**Issue by Ueland** [Amulet-Team/Amulet-Core#165]
**Describe the bug**
It seems that when setting the Text[1-4] properties for a sign, the properties are not saved in the block, causing any text set for a sign to be ignored.

**To Reproduce**
Use the following example code:
```
import amulet
from amulet.api.block import Block
from amulet_nbt import TAG_String, TAG_Int

# Load level, which is a superflat creative world made in Minecraft 1.16.2
level = amulet.load_level("<a flat world>")
game_version = ("java", (1, 16, 2))

sign = Block(
    namespace="minecraft",
    base_name="birch_sign",
    properties={
        "rotation": TAG_String("2"),
        "Text1": TAG_String('{"text":"Hi there","color":"blue"}'),
    },  
)

level.set_version_block(
    192,  # x location
    4,  # y location
    166,  # z location
    "minecraft:overworld",  # dimension
    game_version,
    sign,
)

print(level.get_version_block(192,4,166,"minecraft:overworld", game_version))

# Save and exit
level.save()
level.close()

```

It will then print the following block data:
`(Block(minecraft:birch_sign[rotation="2"]), BlockEntity[minecraft:sign, 0, 0, 0]{NBTFile("":{Text1: "{\"text\":\"\"}", Text2: "{\"text\":\"\"}", Text3: "{\"text\":\"\"}", Text4: "{\"text\":\"\"}"})})
`

Loading up the map in Minecraft shows the correct sign with the correct rotation, only the text is missing.

**Expected behavior**
I would have expected the block data to contain "hi there" and the color definition. And the text "hi there" to appear in-game.

**Comment by gentlegiantJGC** [comment]
You are trying to set block entity data within the block state. You want to create a block entity and set the text data in that
