### ISSUE TITLE
Angle unit mismatch in SelectionBox.transform

### ISSUE THREAD

**Issue by Keluaa** [Amulet-Team/Amulet-Core#195]
The description and the first line of this method are contradicting each other: the description says the rotation is in radians, while the condition only works if it is in degrees. In both branches of the condition the rotation is passed to `transform_matrix` which uses radians.

https://github.com/Amulet-Team/Amulet-Core/blob/88f700c4fbde75cf020b6080833494ace3658aa0/amulet/api/selection/box.py#L714-L725

I don't know if this method is used anywhere, but I happened to stuble upon this while working on a project of mine.

I guess changing the check to this would be a passable fix (at least it fixed my use case):
```python
if all(math.isclose(abs(r) % (numpy.pi / 2), 0) for r in rotation):
```

**Comment by gentlegiantJGC** [comment]
Yes you are correct. I probably initially implemented this in degrees but switched it to radians.

**Comment by gentlegiantJGC** [comment]
Your implementation is good but has a bug when the value is just below the quadrant. Eg 1.57
