### ISSUE TITLE
block generate problem 

### ISSUE THREAD

**Issue by EndrrSB** [Amulet-Team/Amulet-Core#202]
at first i'm a noob of python
and i use it code to generate a glowstone in my flat world, but the glowstone didn't emit light

```python
import amulet
from amulet.api.block import Block

level = amulet.load_level(world_path)
game_version = ("java", (1, 18, 2))

# set a block
block = Block("minecraft", "glowstone")
block_pos = [11,-60,-7]

level.set_version_block(
    block_pos[0],
    block_pos[1],
    block_pos[2],
    "minecraft:overworld",
    game_version,
    block 
)

level.save()

level.close()
```

[![XGNJZq.png](https://s1.ax1x.com/2022/06/01/XGNJZq.png)](https://imgtu.com/i/XGNJZq)

last thank all of your guys develop this project it help a lots !

**Comment by gentlegiantJGC** [comment]
Amulet does not currently recompute lighting.
This is tracked in Amulet-Team/Amulet-Map-Editor#44
