### ISSUE TITLE
[Bug Report] Blocks below 0 coordinates are not copied

### ISSUE THREAD

**Issue by yri066** [Amulet-Team/Amulet-Core#233]
**Describe the bug**
While converting the world from Java to Bedrock, blocks below 0 coordinates are not copied. This happens on Arm Linux, but without errors on X64 Windows.

**To Reproduce**
1. Select Java world
2. Select output Bedrock world
3. Start convert

**Desktop**
 - OS: Linux ARM64
 - CPU: Snapdragon 835
 - Program Versions: 0.9.4-0.10.8
 - Minecraft Version: java 1.18.2-1.19.3 || bedrock 1.18.33-1.19.51
 - Python 3.9.2

**Additional context**
Console output:

```
INFO - Converting world /var/www/Server/world to /var/www/Server/worldConvert
INFO - Converting level /var/www/Server/world to level /var/www/Server/worldConvert
INFO - Converting chunk minecraft:overworld -64, -64
INFO - Converting chunk minecraft:overworld -63, -64
INFO - Converting chunk minecraft:overworld -62, -64
INFO - Converting chunk minecraft:overworld -61, -64
INFO - Converting chunk minecraft:overworld -60, -64
OverflowError: can't convert negative value to char
Exception ignored in: 'amulet_nbt._int.ByteTag._sanitise_value'
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/copy.py", line 153, in deepcopy
    y = copier(memo)
OverflowError: can't convert negative value to char
OverflowError: can't convert negative value to char
Exception ignored in: 'amulet_nbt._int.ByteTag._sanitise_value'
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/copy.py", line 153, in deepcopy
    y = copier(memo)
OverflowError: can't convert negative value to char
OverflowError: can't convert negative value to char
Exception ignored in: 'amulet_nbt._int.ByteTag._sanitise_value'
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/copy.py", line 153, in deepcopy
    y = copier(memo)
OverflowError: can't convert negative value to char
OverflowError: can't convert negative value to char
Exception ignored in: 'amulet_nbt._int.ByteTag._sanitise_value'
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/copy.py", line 153, in deepcopy
    y = copier(memo)
OverflowError: can't convert negative value to char
INFO - Converting chunk minecraft:overworld -59, -64
OverflowError: can't convert negative value to char
Exception ignored in: 'amulet_nbt._int.ByteTag._sanitise_value'
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/copy.py", line 153, in deepcopy
    y = copier(memo)
OverflowError: can't convert negative value to char
OverflowError: can't convert negative value to char
Exception ignored in: 'amulet_nbt._int.ByteTag._sanitise_value'
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/copy.py", line 153, in deepcopy
    y = copier(memo)
OverflowError: can't convert negative value to char
OverflowError: can't convert negative value to char
Exception ignored in: 'amulet_nbt._int.ByteTag._sanitise_value'
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/copy.py", line 153, in deepcopy
    y = copier(memo)
OverflowError: can't convert negative value to char
OverflowError: can't convert negative value to char
Exception ignored in: 'amulet_nbt._int.ByteTag._sanitise_value'
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/copy.py", line 153, in deepcopy
    y = copier(memo)
OverflowError: can't convert negative value to char

...

INFO - Converting chunk minecraft:the_nether 24, 31
INFO - Converting chunk minecraft:the_nether 25, 31
INFO - Converting chunk minecraft:the_nether 26, 31
INFO - Converting chunk minecraft:the_nether 27, 31
INFO - Converting chunk minecraft:the_nether 28, 31
INFO - Saving changes to level /var/www/Server/worldConvert
INFO - Finished saving changes to level /var/www/Server/worldConvert
INFO - Finished converting world /var/www/Server/world to /var/www/Server/worldConvert

```

**Comment by gentlegiantJGC** [comment]
Looks like char is unsigned by default on some compilers.

**Comment by yri066** [comment]
Hi, I installed myself a branch with a bug fix, now the conversion works well. Thank you very much.

**Comment by Max-RM** [comment]
@yri066 

> * OS: Linux ARM64
> * CPU: Snapdragon 835

Как вы вообще смогли запустить Amulet Map Editor на смартфоне с рабочим 3d editor?  Это считалось невозможным из-за [Этого](https://github.com/Amulet-Team/Amulet-Map-Editor/issues/449#issuecomment-1382711342)  
![IMG_20230203_103322](https://user-images.githubusercontent.com/81485476/216520625-a0c18955-1a96-4698-a13b-c7024509b98a.jpg)
Видимо вы используете Linux ARM нативно как родную систему, а не через Linux Deploy/Termux из-за чего ошибки указанной выше могло вообще не произойти из-за того что в нативно установленной системе будут правильные видео драйвера, или у вас всë таки была ошибка, но вы смогли как-то еë решить, в таком случае мне очень хотелось бы узнать как устранить эту ошибку. 

Кстати есть одна проблема. GentlegiantGJC говорил,  что Amulet перейдëт с WX на QT, там будет использован пакет PySide6 а он просто не портирован на ARM64 попытки установить его через команду не будут работать, сборка из исходников тоже не работает. Так что Amulet переписанный на QT похоже не будет поддерживать Linux ARM и с этим нужно что-то делать.

**Comment by yri066** [comment]
@Max-RM 
Привет, я использую Amulet Map Editor вместе bedrock-viz для создания карты (Amulet ME в основном использую без графического интерфейса, смог добавить аргументы запуски для использования конвертера из консоли).

Ваше сообщение заинтересовало меня, открыл 3D редактор и столкнулся с тем что он постоянно показывает начало загрузки ресурсов и ничего дальше не происходило.
<details><summary>Cкриншот</summary>

![image](https://user-images.githubusercontent.com/26645205/216535016-23fa9704-72f5-4715-9e39-70086cc49ae9.png)
</details>

Решил посмотреть список установленных пакетов с Mesa, после чего установил пакет ```mesa-opencl-icd``` (читал что эти библиотеки использует Headless Chrome)
<details><summary>Список пакетов</summary>

![image](https://user-images.githubusercontent.com/26645205/216537040-b86e0049-7e0e-4098-aad2-7bfb45ddae6f.png)
</details>

После этого 3D редактор загрузился и начал работать, только при этом пропадает интерфейс.
Демонстрация работы: https://youtu.be/LEey9TXKtH4

**Comment by Max-RM** [comment]
> Решил посмотреть список установленных пакетов с Mesa, после чего установил пакет `mesa-opencl-icd` (читал что эти библиотеки использует Headless Chrome в Linux )
> 
> Список пакетов

Так, интересный результат. Думаю стоит установить эти библиотеки и тогда должно заработать

**Comment by Max-RM** [comment]
> Список пакетов

Похоже не все пакеты могут быть установлены без ошибок. Придëтся из исходников собирать. 

Это ваш тег в телеграмме? @yri066 там по легче будет переписываться

**Comment by yri066** [comment]
Да

**Comment by yri066** [comment]
В дополнение, информация о системе.
![image](https://user-images.githubusercontent.com/26645205/216557909-adf25279-4b2f-4a43-84d2-b2baafa5406b.png)

**Comment by Max-RM** [comment]
> В дополнение, информация о системе.

Да спасибо. Так то по сути и я должен был установить Kali чтобы получить тот же результат. Но к сожалению она не работает в Linux Deploy, так что придëтся использовать только Debian.

**Comment by Max-RM** [comment]
> Список пакетов

Пока есть проблемы с 3 пакетами

librust-osmesa-sys-dev
mesa-utils-bin
mesaflash

Если 2 последних пакета ещë можно установить скачав deb пакеты. То первый ни в какую не идëт. Сначала просит установить кучу других дополнительных пакетов чтобы установить его, а после уже и эти пакеты который нужны для установки первого с разными ошибками. То пишет ошибку, что нет пакета по этому придëтся использовать не apt install а установку из deb, то просто какие-нибудь ошибки. 

Так вот есть проблема, что даже если установить эти  
librust-osmesa-sys-dev
mesa-utils-bin
mesaflash
То возможно  3d editor в Amulet всë равно не заработает и в итоге все мучения были зря. У вас были проблемы с установкой этих пакетов или на Kali всë установилось без проблем? 

И ещë вопрос у вас только по VNC с ПК можно запустить Amulet или с самого экрана телефона тоже можно? Просто если с самого телефона не запустится, то особо смысла пытаться дальше что-то делать нету.

**Comment by Max-RM** [comment]
> Запускается только через vnc. Почти все пакеты были сразу установлены в системе. Вроде, напрямую вывести изображение из линукс на дисплей телефона не представляется возможным.

Блин. Ну ладно, тогда буду искать другие пути. 

Но по поводу QT. Однажды выпустят Amulet на QT и при вводе команды обновления он попытается установить пакет PySide6 который не поддерживает Linux ARM. Что тогда будете делать?

**Comment by Max-RM** [comment]
> Ничего, я обычно конвертирую через консоль.

Так новая версия при обновлении просто не установиться без этого пакета. Или если как-то костыльно поставить то будет при старте выдавать ошибку

**Comment by yri066** [comment]
По большей части, могу установить обновленные пакеты по отдельности, т.к. я использую функцию конвертации в обход GUI, то могу обойтись без обновления самого Amulet ME.

**Comment by yri066** [comment]
По поводу поддержки QT и PySide6, мне благополучно удалось запустить на Linux ARM 
[Demo](https://github.com/Amulet-Team/Amulet-Map-Editor/issues/127#issuecomment-1416711771)

**Comment by Max-RM** [comment]
> По поводу поддержки QT и PySide6, мне благополучно удалось запустить на Linux ARM [Demo](https://github.com/Amulet-Team/Amulet-Map-Editor/issues/127#issuecomment-1416711771)

А как была произведена установка PySide6? 

Через исходники или через команду? Просто у меня и в Ubuntu и Debian при вводе команды python3.9 -m pip install PySide6 он пишет 

root@localhost:/home/Max# python3.9 -m pip install PySide6
ERROR: Could not find a version that satisfies the requirement PySide6 (from versions: none)
ERROR: No matching distribution found for PySide6

**Comment by yri066** [comment]
Через исходники

**Comment by Max-RM** [comment]
> Через исходники

Ну в этом тоже есть проблема. Не пойму как именно этот пакет установить из исходников. С остальными проблем особо не было, а здесь ни в какую не идëт

**Comment by Max-RM** [comment]
> Через исходники

Есть где-нибудь инструкция по установке из исходников?

**Comment by yri066** [comment]
Для компиляции использовал этот скрипт https://gitlab.com/-/snippets/2432339
Но пришлось решить несколько проблем:
Шаг 2 пришлось пропустить, т.к. возникла ошибка с добавлением репозитория
Шаг 5 или 6 возникла примерно такая ошибка: Unknown CMake command "check_for_ulimit".
В указанном файле, в начале в ручную добавил:
```
function(check_for_ulimit)
endfunction()
``` 
Шаг 7 погуглил как решить проблему с ```venv```
Шаг 10 заменил `build` на `install`
Шаг 11,12 пропустил

**Comment by Max-RM** [comment]
> https://gitlab.com/-/snippets/2432339

О, я уже это видел. Только не смог собрать используя эту инструкцию. Наверное стоит попробовать сново

**Comment by yri066** [comment]
Главное отступление на 8 пункте

**Comment by Max-RM** [comment]
> Шаг

С 3 шагом тоже проблемы есть. Какой-то критин заблокировал загрузку с русских ip приходиться через обходные методы грузить этот 700 мб файл

**Comment by Max-RM** [comment]
> Шаг

А что за директория ~ ? 

Просто чтобы знать куда нужно поместить сказанный файл?

**Comment by Max-RM** [comment]
Теперь всë работает

[Демонстрация](https://youtu.be/438FJJjgkT8)

**Comment by Max-RM** [comment]
Ещë спустя столько времени мне удалось запустить Amulet-editor на Android практически нативно.

https://youtu.be/SorPnrU6cGg
https://youtu.be/Evuh3FS3fY4

Теперь я могу управлять камерой и двигаться в пространстве.
