### ISSUE TITLE
Any new updates on the old lighting issue?

### ISSUE THREAD

**Issue by FelixFourcolor** [Amulet-Team/Amulet-Core#275]
The issue goes way back since [https://github.com/Amulet-Team/Amulet-Map-Editor/issues/44](https://github.com/Amulet-Team/Amulet-Map-Editor/issues/44), and has been reopened multiple times.

I see that #121 attempted to partially fix it by adding a pre-save operation. I have added it to my code, but can hardly tell any difference.

[A comment in the old thread](https://github.com/Amulet-Team/Amulet-Map-Editor/issues/44#issuecomment-1179728504) seems to provide a solution that only applies to the amulet editor. Since I only use the python library, my solution has been running the code then `Edit > Optimize World > Erase Cached Data`, which definitely works but is inconvenient. I wish there were a function in amulet-core that does exactly that.

Since it's been a while, are there any updates on this bug?

**Comment by gentlegiantJGC** [comment]
It is not something we currently support

**Comment by FelixFourcolor** [comment]
That's sad to hear. I hope someday it will be fixed.
