### ISSUE TITLE
[Bug] Unable to read player's rotation in MC Java

### ISSUE THREAD

**Issue by FelixFourcolor** [Amulet-Team/Amulet-Core#276]
Issue: In Minecraft Java, player's rotation is always `(0.0, 0.0)`.

Minimal example:
```
import amulet

level = amulet.load_level("World")  # World exists in cwd

# get all players
players = tuple(level.get_player(i) for i in level.all_player_ids())

print(players)
for p in players:
    print(p.rotation)
```

Result:
```
INFO - PyMCTranslate Version 257
INFO - Loading level World
(Player(~local_player, minecraft:overworld, (448.23636334102594, 72.0, 14.437218714980915), (0.0, 0.0)), Player(b44f7dfd-c8d5-4330-809d-0f4aaf2a8f41, minecraft:overworld, (448.23636334102594, 72.0, 14.437218714980915), (0.0, 0.0)))
(0.0, 0.0)
(0.0, 0.0)
```
Seems like every other attribute works: player_id, dimension, location; except rotation is always `(0.0, 0.0)`.

This issue only exists for Java edition. Bedrock works as expected.

-------------------
System info

amulet-core 1.9.20
python 3.11
Linux & Windows

**Comment by FelixFourcolor** [comment]
I've been looking into this issue.

The code that retrieves player's rotation on Java: [amulet.level.format.anvil_world.format.py](https://github.com/Amulet-Team/Amulet-Core/blob/1.0/amulet/level/formats/anvil_world/format.py) (around line 700)
```
def _load_player(self, player_id: str) -> Player:
    ...

    rot_data = player_nbt.get("Rotation")
    if (
        isinstance(rot_data, ListTag)
        and len(rot_data) == 2
        and rot_data.list_data_type == DoubleTag.tag_id
    ):
        rotation = tuple(map(float, rot_data))
        rotation = tuple(
            p if -100_000_000 <= p <= 100_000_000 else 0.0 for p in rotation
        )
    else:
        rotation = (0.0, 0.0)
```

It's always the third condition that fails, which makes `rotation = (0.0, 0.0)`. Specfically `rot_data.list_data_type` is 5, and `DoubleTag.tag_id` is 6. When I remove the third condition, everything works. I've tested on many different world saves, with Java 1.18-20, on both Linux and Windows (although my tests are by no means exhaustive).

I'm curious, what is the condition `rot_data.list_data_type == DoubleTag.tag_id` for? Is it safe to just remove it?

Anyway, I hope it helps.

**Comment by gentlegiantJGC** [comment]
Yeh looks like rotation is floats not doubles
