### ISSUE TITLE
Amulet Dont Support 1.20.2+ versions

### ISSUE THREAD

**Issue by 3093FengMing** [Amulet-Team/Amulet-Core#278]
**Describe the bug**
When I use `amulet.load_level`, the console tell me `amulet.api.errors.LoaderNoneMatched: Could not find a matching interface for ('java', 3690)`

**To Reproduce**
1. Prepare a save with a snapshot version greater than 1.20.2(23w40a+).
2. Use `amulet.load_level`.
3. An error has occurred.(`Could not find a matching interface for ('java', 3690)`)

**Expected behavior**
Load world normally.

**Screenshots**
No.

**Desktop (please complete the following information):**
 - OS: Windows 10 22H2
 - Amulet 1.9.20(date 2023-09-29T11:29:40+0100)

**Additional context**
No.

**Comment by gentlegiantJGC** [comment]
We don't support snapshot versions

**Comment by gentlegiantJGC** [comment]
If you are running from source you can increase this number to enable support for it but if the chunk format has changed it may corrupt the world.
https://github.com/Amulet-Team/Amulet-Core/blob/1.0/amulet/level/interfaces/chunk/anvil/anvil_3463.py#L16
