### ISSUE TITLE
About the export .mcstructure file

### ISSUE THREAD

**Issue by jojojo805** [Amulet-Team/Amulet-Core#284]
```py
def main():
    world = amulet.load_level("C:/Users/jo1/AppData/Roaming/MinecraftPE_Netease/minecraftWorlds/java2")
    world_dimesion = "minecraft:overworld"
    version = (1, 18, 30)
    path = "C:/Users/jo1/AppData/Roaming/MinecraftPE_Netease/exported_structures/test.mcstructure"
    selection = SelectionGroup(SelectionBox((0, 50, 0), (500, 100, 500)))
    wrapper = MCStructureFormatWrapper(path)
    wrapper.create_and_open("bedrock", version, selection, True)

    wrapper.translation_manager = world.translation_manager
    wrapper_dimension = wrapper.dimensions[0]



    for (cx, cz) in selection.chunk_locations():
        try:
            chunk = world.level_wrapper.load_chunk(cx, cz, world_dimesion)
            wrapper.commit_chunk(chunk, wrapper_dimension)
        except ChunkLoadError:
            print("ChunkLoadError")

    wrapper.save()
    wrapper.close()


if __name__ == '__main__':
    main()
```

When I run this code, I get the.mcstructure file in the wrong format, When you open it with NBT Studio, you find "minecraft:andesite" in the block_palette, but the palette should actually be "name:minecraft:stone state:stone_type:andesite" Similar to this sentence, so I lost andesite when I converted, is there something wrong with the code I wrote? I want to change the code so that the exported file looks like it was saved in a structure block. Can someone help me?

![5446BCC8-2555-479b-9CB9-59DDFE0C6229](https://github.com/Amulet-Team/Amulet-Core/assets/75937179/e68291c9-1d4d-4ba4-bee7-67715b1693c6)
![44241B63-3FB3-4865-894A-06B2DBB2DB80](https://github.com/Amulet-Team/Amulet-Core/assets/75937179/6b5f134a-97e7-446e-adee-eed2a0e44e5d)

**Comment by gentlegiantJGC** [comment]
I will handle this in Amulet-Team/Amulet-Map-Editor#1033
