### ISSUE TITLE
[Bug report] The coordinates of the block in blocks_tick was mistakenly changed while saving without doing not make any changes to it

### ISSUE THREAD

**Issue by 3093FengMing** [Amulet-Team/Amulet-Core#286]
**Describe the bug**
The coordinates of the block in blocks_tick was mistakenly changed while saving without doing not make any changes to it.
This seems to be the code about decode `block_ticks`, as you can see that it has been marked with TODO.

https://github.com/Amulet-Team/Amulet-Core/blob/ac72c15417c9bd86d9332d7a6488311ad1cb30ab/amulet/level/interfaces/chunk/anvil/anvil_1444.py#L159

**To Reproduce**
1. Load a save.
2. Make some changes to the `block_entities`, but do not change the coordinates.
3. Save it and you can see that the coordinates of the block in the `blocks_tick` has been changed

**Expected behavior**
`blocks_tick` should not have made any changes.

**Screenshots**
[![c.png](https://i.postimg.cc/2ypMVRkH/c.png)](https://postimg.cc/R6RXDYnf)

**Desktop (please complete the following information):**
 - OS: Window 10 22H2 19045.2006
 - Program Version: Amulet Core 1.9.21

**Additional context**
Here is the region file and test command block is in chunk [0,0].
[Google Drive](https://drive.google.com/file/d/1l8GU6L1pmVo2DcFzETIQab6NRrI4HWMF/view?usp=sharing)

**Comment by PREMIEREHELL** [comment]
found the issue, simple typo , https://github.com/Amulet-Team/Amulet-Core/blob/ac72c15417c9bd86d9332d7a6488311ad1cb30ab/amulet/level/interfaces/chunk/anvil/anvil_na.py#L540
