### ISSUE TITLE
Fix chunks that were not saved in the world folder

### ISSUE THREAD

**Issue by naor2013** [Amulet-Team/Amulet-Core#4]
We have 2 cases of that.
1. We don't have the needed region file
2. We have the region file but the chunk data is missing

We can either error which will ruin any operations even if some chunks exist, we can fill with air but it might not be what the users expect.

**Comment by gentlegiantJGC** [comment]
This has been implemented that if a chunk is requested that does not exist in the database ChunkDoesNotExist will be thrown. If you try writing to a region that does not exist (Java only) the Format class will create it. I believe this issue has been fixed so I am closing this issue.
