### ISSUE TITLE
[Feature] Use Gradle to build Amulet on any OS

### ISSUE THREAD

**Issue by Tsoccerguy3** [Amulet-Team/Amulet-Core#46]
Use Gradle to download all dependencies , determine what OS platform and build Amulet

**Comment by Podshot** [comment]
I'll look into use this, but it will depend on nicely Gradle will work with Python things and the build process that we'll use.

**Comment by freundTech** [comment]
There is PyGradle, an open source gradle plugin for building python, written by linkedIn.
I haven't used it yet (Only used gradle for java and kotlin), but I think going with setuptools instead of gradle, as recommended by the Python Packaging User Guide, would probably be better.

**Comment by gentlegiantJGC** [comment]
@Podshot Is this still an issue we need to solve?
