### ISSUE TITLE
[WIP] Renderer and UI

### ISSUE THREAD

**Issue by Podshot** [Amulet-Team/Amulet-Core#51]
Implement a renderer for our UI, it would be preferred to have good performance while also being understandable and easy to extend to account for possible additions and changes as needed. Currently, we have a prototype written with one library and candidates for other options.

Options so far:
- Panda3D - https://www.panda3d.org/
    - [Prototype](https://gist.github.com/Podshot/ff76be518cb7cfe35c938c23ed5161c5)
    - Requires the Minecraft-Model-Library by @gentlegiantJGC located [here](https://github.com/gentlegiantJGC/Minecraft-Model-Reader)
- Pyglet - https://pyglet.readthedocs.io/en/pyglet-1.3-maintenance/
- Godot Engine with Python Scripting - https://godotengine.org/
    - Python Bindings located [here](https://github.com/touilleMan/godot-python)
- Unreal Engine - https://www.unrealengine.com/
   - Using C++/Python bindings [docs](https://docs.unrealengine.com/en-US/PythonAPI/index.html)
   - 3rd Party Python Support [Github](https://github.com/20tab/UnrealEnginePython)

I have also started prototype work on a raycast system to avoid being tied to a physics engine and/or framework in case we decided to switch to a better or more suitable framework. That can be found [here](https://gist.github.com/Podshot/2b79bda7a549a23a0fee45fe3d68b4c6)

If you think another framework or engine would be more suitable and has Python 3+ bindings (>=3.7 specifically), please post a link to it here so we can take a look at it and add it to the list above!

**Comment by Ex-Ark** [comment]
Looking forward to this feature 👍 

I tried running the prototype locally , but I appear to be missing some files (assets maybe ?)

I downloaded  gentlegiant Minecraft-Model-Library dependency, but it seems it contains no assets in the repo (what about those hard coded assets path anyway)
```
File ".\src\amulet4.py", line 91, in __init__
    with open(r"blocks.json") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'blocks.json'
```
My `pip list` output :
```
Package         Version
--------------- -------
future          0.17.1
NBT             1.5.0
numpy           1.15.2
panda3d         1.10.3
Pillow          6.0.0
pip             18.0
prompt-toolkit  2.0.4
pyglet          1.3.2
PyTexturePacker 1.0.1
setuptools      40.8.0
six             1.12.0
wcwidth         0.1.7
```

keep up the good work !

**Comment by gentlegiantJGC** [comment]
blocks.json is a file output by the server when given some specific command arguments. I guess this will be automated in the final thing.

https://wiki.vg/Data_Generators

**Comment by NewDefectus** [comment]
Is this project discontinued? If not, I think it would be best to use PyGame for rendering, similarly to MCEdit.

**Comment by Podshot** [comment]
@NewDefectus The project is not discontinued! We're currently working on our renderer and figuring out how approach that, so we aren't focusing as much on this until we can at least render blocks with their appropriate textures and models.

As for using PyGame, we decided to not use it and/or consider it due to the fact that it's still a little unstable on OS X and that it isn't really suited for dedicated 3D rendering. On top of that, since this project is completely separate from MCEdit/MCEdit-Unified, we wanted to use newer, more suited libraries for this task and not just make a "continuation" of MCEdit-Unified (IE: something that would be akin to a "MCEdit-Unified 2")

**Comment by NewDefectus** [comment]
I see. Thanks for the reply! Looking forward to see the final product :)

**Comment by gentlegiantJGC** [comment]
I am going to close this issue since we have now settled on directly using pyOpenGL
