### ISSUE TITLE
Unable to install on macOS

### ISSUE THREAD

**Issue by Thepenguin9** [Amulet-Team/Amulet-Core#56]
**Describe the bug**
When following the install guide in README.md pip will error with a cryptic error message

**To Reproduce**
1. Follow the macOS guide up to step 4
2. Run step 4 in console
3. See error

**Expected behavior**
App builds succesfully

**Screenshots**
![image](https://user-images.githubusercontent.com/6556747/66258859-02405700-e7a2-11e9-9333-63b2fd925506.png)

**Desktop (please complete the following information):**
 - OS: macOS Mojave
 - Program Version: Commit cd8fab4

**Additional context**
I am using python and pip version 3

**Comment by Podshot** [comment]
If you are using a virtual environment, try updating pip by running `pip install --upgrade pip` and then re-run the install steps. If that doesn't work, verify that you have Apple's xcode installed (needed for you to get gcc).

If getting xcode isn't an option or it doesn't solve the issue, try running either of these two commands: 

- `pip install --no-use-pep517 git+git://github.com/Amulet-Team/Amulet-NBT.git`
- `pip install --no-binary git+git://github.com/Amulet-Team/Amulet-NBT.git`

**Comment by Thepenguin9** [comment]
I currently don't have access to this machine, but I tried each of those commands both in and out of the virtual environment and either ended up with the PEP 517 error or a generic error

**Comment by Podshot** [comment]
Ok, I'll see if I can get continuous builds going for the NBT module and hopefully that will fix the installation issue

**Comment by Thepenguin9** [comment]
I will try and get access to the machine to test that. 
In the meantime, do you have a guide you can point me to showing how to install the module? I am but a noob still with python sadly

**Comment by Podshot** [comment]
Here's a link to a [StackOverflow answer](https://stackoverflow.com/a/27909082)

In summary, just run `pip install <path to the .whl file>` in your terminal, where the path to the file replaces the angle brackets and their content

**Comment by gentlegiantJGC** [comment]
I am going to close this issue for now because it is out of date. We will add back the build information at some point in the future. If you experiences issues there please open a new issue.
