### ISSUE TITLE
Unable to Install on Ununtu 19.10

### ISSUE THREAD

**Issue by Antonios-P** [Amulet-Team/Amulet-Core#58]
Greetings. I tried to install the editor yesterday, and I was having a lot of trouble getting it installed. I installed all the prerequisites (numpy, etc.) but after the virtual environment didn't activate. The console said that it wasn't a directory. Also, the documentation link is dead, so I couldn't go to it. Fixing that too would be nice. Thanks for your time and help.

**Comment by Podshot** [comment]
Can you give us the commands you used to download the source code and install the requirements as well as the output from them?

**Comment by Antonios-P** [comment]
Sure. I first cloned the source code with ```git clone https://github.com/Amulet-Team/Amulet-Map-Editor.git```. I couldn't find the output of that command. I then changed the working directory to be inside of the repo folder with ```cd Amulet-Map-Editor```. This didn't output anything, but it went into the directory correctly without a hiccup. I updated my sources with ```sudo apt-get update``` just-in-case and because I had python 3.7 already installed, i just did ```python3.7 --version``` to make sure that I had it installed correctly. This output: ```Python 3.7.5rc1```. The python environment is where things got a little dicey. I created the environment using ```python3.7 -m venv ENV```. It didn't output anything. I went to activate the environment with ```source /ENV/bin/activate```, but I didn't get an output. The console said something along the lines of "<path-to-file> is not a directory" if you knwo what I mean. I decided to move on however. I started to install the requirements. I did this by ```sudo pip3 install -r requirements.txt```. This output: https://pastebin.com/fdxRXEnMI didn't do the pre-commit install. I then installed the dev requirements with ```sudo pip3 install -r requirements-dev.txt```. This output: https://pastebin.com/GjEMhdYF. This is where I stopped because there were no instructions on what to do next and the documentation link was broken.

**Comment by juozaspo** [comment]
> I went to activate the environment with source /ENV/bin/activate, but I didn't get an output.
That's a mistake in README.md, the command tries to access a folder to root directory of the system and fails, it should corrected to `./ENV/bin/activate` or `ENV/bin/activate` (w/o a leading slash or with a leading dot)
More information in #60, where I partly succeeded to run it.

**Comment by Podshot** [comment]
@Antonios-P Could you try installing Amulet-Core again? We've updated our `setup.py` and the installation process should be less of a headache
