### ISSUE TITLE
Add in support for chunk data saved in .mcc files

### ISSUE THREAD

**Issue by Podshot** [Amulet-Team/Amulet-Core#70]
Java 1.15 introduced an additional file format for chunks that exceed the 1MB limit for chunk data that is currently present in the Anvil region format. If a chunk is larger than 1MB, then it's chunk data will be saved to an additional file named `c.<cx>.<cz>.mcc` where `<cx>` and `<cz>` denote the chunk coordinates. The chunk data in this new file is still compressed with zlib.

Notable divergences:
- In the `.mca` file for the region, the chunk data is saved as one byte, with the value `0x82` [1]. This is the indicator that the chunk data is saved in the additional file along with the chunk data length being 1 (this latter fact shouldn't be be the sole indicator, from [1])

Changes Needed:
- [x] Have Amulet recognize when it needs to load chunk data from the additional chunk file
- [ ] Determine if Minecraft has issues with the additional file holding less than 1MB of data (due to trimming the data in some way outside the game) when re-loading the world, have Amulet behave accordingly and re-integrate the data into the original `.mca` file

Sources:
1. https://www.reddit.com/r/technicalminecraft/comments/e4wxb6/a_new_save_file_format_for_java_edition_115_has/?ref=share&ref_source=link

**Comment by gentlegiantJGC** [comment]
Amulet reads all the data in the mca file and at the point of accessing a chunk data if the high bit in the compression type byte is set it will try accessing it from the external file.
Upon saving it will check the size of each chunk and save it out accordingly.
Finally it will clean up any orphaned mcc files.
8b2776024795a2f564a8c696baf9d691f79f0a38
